global:
  scrape_interval: 60s
  evaluation_interval: 60s

alerting:
  alertmanagers:
    - static_configs:
        - targets:

rule_files:

scrape_configs:
  - job_name: "Jenkins"
    metrics_path: "/prometheus/"
    scheme: http
    tls_config:
            insecure_skip_verify: true
    basic_auth:
            username: 'pD7Dt2zw3yt56MYFIBoCkzG51UeGyPTY'
            password: '***REMOVED***'
    static_configs:
            - targets: ["localhost:8081"]

  - job_name: "Prometheus"
    metrics_path: "/metrics"
    scheme: http
    static_configs:
            - targets: ["localhost:9090", "localhost:9100"]

  - job_name: "Cadvisor"
    metrics_path: "/metrics"
    scheme: http
    static_configs:
            - targets: ["localhost:8100"]